# Generated by Django 2.2.10 on 2020-03-18 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_auto_20200318_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='data_appended',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
