# Generated by Django 2.2.10 on 2020-03-20 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_auto_20200320_1111'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='data_appended',
            new_name='date_appended',
        ),
    ]
